name             'rabbitmq-in-depth'
maintainer       'Gavin M. Roy'
maintainer_email 'gavinmroy@gmail.com'
license          'BSD'
description      'Set up the RabbitMQ in Depth dependencies'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
depends          'apt'
depends          'git'
depends          'python'
depends          'rabbitmq'
depends          'supervisor'
depends          'x509'
depends          'zeromq'